import Head from "next/head";
import Image from "next/image";
import Filter from "../../components/Filter";
import styles from "../../styles/Home.module.css";

export default function card({ events }) {
  console.log(events);

  return (
    <div>
      <Head>
        <title>React-Select with filter search</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className={styles.main}>
        <h1>React-Select with filter search</h1>

        <Filter />
        {events.map((evt) => (
          <div key={evt.id} className={styles.card}>
            userId: {evt.userId}
            <br />
            {evt.title}
          </div>
        ))}
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
}

export async function getStaticProps() {
  const res = await fetch("https://jsonplaceholder.typicode.com/posts");
  const events = await res.json();
  console.log(events);
  return {
    // 這裡用Props是因為data現在在server side 需在function Home中output
    props: { events },
    revalidate: 1,
  };
}
